# Generated by Django 4.2 on 2023-06-17 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=100)),
                ('employee_id', models.UUIDField(blank=True, default=uuid.UUID('8d9a2565-e90b-446f-86c8-4acb8d7a6faf'), editable=False, unique=True)),
                ('description', models.TextField(max_length=100)),
                ('hiring_date', models.DateField()),
                ('position', models.CharField(max_length=50)),
            ],
        ),
    ]
