# Generated by Django 4.0 on 2023-06-17 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vacationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('4732289b-cc70-4687-a482-1a991d8814ff'), editable=False, unique=True),
        ),
    ]
